"""Generate AnvilCode icons — hand-drawn anvil in the v2 blue/white palette.

Creates icon.png (512px, transparent) and icon.jpg (512px, dark background).
Run:  python make_icons.py
"""
from pathlib import Path

from PIL import Image, ImageDraw

HERE = Path(__file__).parent
S = 512

# anvil silhouette (union of shapes), y grows downward
TOP_BAR = ("rrect", (96, 118, 416, 168), 14)
HORN = ("poly", [(98, 122), (24, 150), (98, 164)])
BODY = ("poly", [(170, 168), (342, 168), (318, 250), (194, 250)])
BASE = ("poly", [(152, 250), (360, 250), (392, 316), (120, 316)])
FOOT = ("rrect", (100, 316, 412, 366), 14)
SPARK = ("poly", [(430, 60), (436, 76), (452, 82), (436, 88), (430, 104), (424, 88), (408, 82), (424, 76)])

# v2 palette: light blue -> white, on deep navy
BG_TOP = (13, 20, 34)
BG_BOTTOM = (7, 11, 20)
ANVIL_TOP = (125, 211, 252)   # light blue  (#7dd3fc)
ANVIL_BOTTOM = (248, 250, 252)  # white      (#f8fafc)


def v_gradient(size, top, bottom, y0, y1):
    img = Image.new("RGBA", size, top + (255,))
    dr = ImageDraw.Draw(img)
    for y in range(size[1]):
        t = min(1.0, max(0.0, (y - y0) / max(1, y1 - y0)))
        col = tuple(int(top[i] + (bottom[i] - top[i]) * t) for i in range(3)) + (255,)
        dr.line([(0, y), (size[0], y)], fill=col)
    return img


def draw_shape(dr, shape, fill=255):
    kind, geom, *rest = shape
    if kind == "rrect":
        dr.rounded_rectangle(geom, radius=rest[0], fill=fill)
    else:
        dr.polygon(geom, fill=fill)


def generate_art(image, px_size: int = 32):
    """Downscale the icon and write it as RLE half-block rows for the TUI banner.

    Output (anvil/_art.py) is a pure-Python literal — the terminal banner needs
    no image library at runtime. Rows are (top_rgb|None, bottom_rgb|None, count).
    """
    img = image.resize((px_size, px_size), Image.LANCZOS).convert("RGBA")
    px = img.load()

    def col(p):
        return [p[0], p[1], p[2]] if p[3] >= 128 else None

    rows = []
    for y in range(0, px_size, 2):
        row = []
        run = None
        for x in range(px_size):
            cur = (col(px[x, y]), col(px[x, y + 1]))
            if run and run[0] == cur[0] and run[1] == cur[1]:
                run[2] += 1
            else:
                run = [cur[0], cur[1], 1]
                row.append(run)
        rows.append(row)

    art_file = HERE / "anvil" / "_art.py"
    art_file.write_text(
        '"""Generated by make_icons.py — half-block pixel art of icon.png (do not edit)."""\n'
        f"PX = {px_size}\nART = {rows!r}\n", encoding="utf-8")
    print(f"wrote {art_file}")


def main():
    # background: rounded square, deep navy gradient
    bg_mask = Image.new("L", (S, S), 0)
    ImageDraw.Draw(bg_mask).rounded_rectangle([16, 16, S - 16, S - 16], radius=100, fill=255)
    bg_grad = v_gradient((S, S), BG_TOP, BG_BOTTOM, 0, S)
    out = Image.new("RGBA", (S, S), (0, 0, 0, 0))
    out.paste(bg_grad, (0, 0), bg_mask)

    # anvil: light blue -> white through the silhouette mask
    anvil_mask = Image.new("L", (S, S), 0)
    dr = ImageDraw.Draw(anvil_mask)
    for shape in (TOP_BAR, HORN, BODY, BASE, FOOT):
        draw_shape(dr, shape)
    anvil_grad = v_gradient((S, S), ANVIL_TOP, ANVIL_BOTTOM, 110, 380)
    out.paste(anvil_grad, (0, 0), anvil_mask)

    # white spark accent
    ImageDraw.Draw(out).polygon(SPARK[1], fill=(248, 250, 252, 255))

    out.save(HERE / "icon.png")
    flat = Image.new("RGB", (S, S), BG_BOTTOM)
    flat.paste(out, (0, 0), out)
    flat.save(HERE / "icon.jpg", quality=92)
    print(f"wrote {HERE / 'icon.png'} and {HERE / 'icon.jpg'}")
    generate_art(out)


if __name__ == "__main__":
    main()
