"""Terminal UI — panels, streaming (throttled for speed), confirmations, banner."""
from __future__ import annotations

import difflib
import time

from rich import box
from rich.console import Console, Group
from rich.live import Live
from rich.markdown import Markdown
from rich.panel import Panel
from rich.syntax import Syntax
from rich.table import Table
from rich.text import Text
from rich.theme import Theme

from . import theme
from .theme import G

VERSION = "2.2.0"

# words the approval prompt understands -> canonical answer
CONFIRM_MAP = {
    "y": "y", "yes": "y",
    "n": "n", "no": "n",
    "a": "a", "al": "a", "always": "a", "always yes": "a", "always this session": "a",
    "v": "v", "nv": "v", "never": "v", "always no": "v", "never this session": "v",
}


def colorize_diff(diff_text: str) -> Text:
    out = Text()
    for line in (diff_text or "").splitlines():
        if line.startswith("+++") or line.startswith("---"):
            out.append(line + "\n", style="bold")
        elif line.startswith("@@"):
            out.append(line + "\n", style="cyan")
        elif line.startswith("+"):
            out.append(line + "\n", style="green")
        elif line.startswith("-"):
            out.append(line + "\n", style="red")
        else:
            out.append(line + "\n", style="dim")
    return out


class StreamView:
    """Live-renders the reply while it streams.

    Re-parsing markdown on every token is what made v1 feel laggy —
    now the Live display only refreshes every ~90 ms or at the end.
    """

    REFRESH_EVERY = 0.09  # seconds

    def __init__(self, console: Console):
        self.console = console
        self._buf: list[str] = []
        self._reason_tail = ""
        self._live: Live | None = None
        self._status = None
        self._last = 0.0

    def start(self):
        self._status = self.console.status("anvil is working", spinner="arc")
        self._status.start()

    def on_reasoning(self, delta: str):
        self._reason_tail = (self._reason_tail + delta)[-200:]
        if self._status:
            self._status.update(f"thinking… [dim]{self._reason_tail[-110:].strip()}[/dim]")

    def on_content(self, delta: str):
        if self._status:
            self._status.stop()
            self._status = None
        if self._live is None:
            self._live = Live(console=self.console, refresh_per_second=14,
                              vertical_overflow="visible")
            self._live.start()
        self._buf.append(delta)
        now = time.monotonic()
        if now - self._last >= self.REFRESH_EVERY:
            self._flush()

    def _flush(self):
        if self._live:
            self._live.update(Group(Markdown("".join(self._buf))))
            self._last = time.monotonic()

    def finish(self):
        if self._status:
            self._status.stop()
            self._status = None
        if self._live:
            self._flush()
            self._live.stop()
            self._live = None

    def abort(self):
        self.finish()


class UI:
    def __init__(self):
        self.console = Console(theme=Theme(theme.THEME), highlight=False)

    # ---------------- chrome ----------------

    def banner(self, cfg: dict):
        c = self.console
        w = c.width
        c.print()
        self.pixel_art()
        pad = max(0, (w - theme.WORDMARK_WIDTH) // 2)
        for t in theme.banner_rows():
            c.print(Text(" " * pad) + t)
        c.print()
        status = Text()
        status.append(" mode ", style=f"bold {theme.BLUE}")
        status.append(cfg.get("mode", "ask"), style=f"bold {theme.WHITE}")
        status.append("  ·  ", style="dim")
        status.append("model ", style="dim")
        from . import config
        status.append(config.model_label(cfg["model"]), style=f"bold {theme.BLUE}")
        status.append("  ·  effort ", style="dim")
        status.append(cfg["effort"], style=f"bold {theme.WHITE}")
        status.append("  ·  ", style="dim")
        status.append(str(cfg.get("_cwd", ".")), style="dim")
        status.append("  ·  ", style="dim")
        status.append("/help for commands", style="dim italic")
        c.print(Panel(status, border_style=theme.BLUE_DEEP, box=box.ROUNDED, padding=(0, 1),
                      expand=False), justify="center")

    def pixel_art(self):
        """The anvil icon rendered as terminal pixel art (half-blocks, RLE runs).

        Generated by make_icons.py into anvil/_art.py; silently skipped when absent.
        """
        try:
            from . import _art
        except ImportError:
            return
        w = self.console.width
        pad = max(0, (w - _art.PX) // 2)
        for row in _art.ART:
            t = Text()
            for top, bot, n in row:
                if top is None and bot is None:
                    t.append(" " * n)
                elif bot is None:
                    t.append("▀" * n, style=f"rgb({top[0]},{top[1]},{top[2]})")
                elif top is None:
                    t.append("▄" * n, style=f"rgb({bot[0]},{bot[1]},{bot[2]})")
                else:
                    t.append("▀" * n, style=f"rgb({top[0]},{top[1]},{top[2]})"
                                             f" on rgb({bot[0]},{bot[1]},{bot[2]})")
            self.console.print(Text(" " * pad) + t)

    def first_run_hint(self):
        self.console.print(Panel(
            "[bold]Welcome to AnvilCode.[/]\n"
            "No account needed — just a free HuggingFace token.\n"
            f"Create one at [{theme.BLUE}]https://huggingface.co/settings/tokens[/] "
            "(fine-grained, read access is enough).\n"
            "It is stored locally in [dim]~/.anvilcode/config.json[/].",
            title=f"[{theme.BLUE}]anvil · one-time setup[/]",
            border_style=theme.BLUE, box=box.ROUNDED,
        ))

    # ---------------- small printers ----------------

    def info(self, text: str):
        self.console.print(f"[{theme.BLUE}]{G['info']}[/] {text}")

    def ok(self, text: str):
        self.console.print(f"[{theme.BLUE}]{G['ok']}[/] {text}")

    def warn(self, text: str):
        self.console.print(f"[yellow]{G['warn']}[/] {text}")

    def error(self, text: str):
        self.console.print(f"[bold red]{G['err']} {text}[/]")

    def dim(self, text: str):
        self.console.print(f"[dim]{text}[/]")

    def md(self, text: str):
        self.console.print(Markdown(text))

    def panel(self, title: str, body, border: str = None):
        self.console.print(Panel(body, title=title,
                                 border_style=border or theme.BLUE, box=box.ROUNDED))

    def diff(self, title: str, diff_text: str, note: str = ""):
        body = colorize_diff(diff_text)
        if note:
            body.append(f"\n{note}", style="dim italic")
        self.console.print(Panel(body, title=f"{G['brand']} {title}",
                                 border_style="yellow", box=box.SQUARE))

    def code(self, title: str, code_text: str, lang: str = ""):
        body = Syntax(code_text, lang or "text", word_wrap=True) if lang else Text(code_text)
        self.console.print(Panel(body, title=f"{G['brand']} {title}",
                                 border_style="yellow", box=box.SQUARE))

    # ---------------- agent loop visuals ----------------

    def tool_header(self, name: str, summary: str):
        self.console.print(f"\n[{theme.THEME['tool']}]{G['brand']} {name}[/] [dim]{summary}[/]")

    def tool_result(self, result: str):
        first = (result or "").strip().splitlines()
        head = first[0][:160] if first else "(no output)"
        style = "dim" if result.startswith(("OK", "exit code: 0")) else "yellow"
        self.console.print(f"  [{style}]{G['arrow']} {head}[/]")

    def usage_line(self, seconds, tin, tout, tools):
        def k(n):
            return f"{n / 1000:.1f}k" if n >= 1000 else str(n)
        parts = [f"{seconds:.1f}s"]
        if tin:
            parts.append(f"tok in {k(tin)}")
        if tout:
            parts.append(f"tok out {k(tout)}")
        if tools:
            parts.append(f"tools {tools}")
        self.console.print(Text("  " + "  |  ".join(parts), style="dim"))

    def show_reasoning(self, text: str):
        body = text if len(text) <= 4000 else text[:2000] + "\n…\n" + text[-2000:]
        self.console.print(Panel(Text(body, style="dim italic"),
                                 title=f"{G['brand']} reasoning",
                                 border_style="grey58", box=box.ROUNDED))

    def table(self, title: str | None = None) -> Table:
        t = Table(box=box.SIMPLE, show_lines=False, title=title,
                  title_style=f"bold {theme.BLUE}")
        return t

    # ---------------- interaction ----------------

    def show_plan(self, title: str, body, note: str = ""):
        """Show what WOULD happen (diff/command) when a mode runs it without asking."""
        if note:
            body = Group(body, Text(note, style="dim italic"))
        self.console.print(Panel(body, title=f"{G['brand']} {title}",
                                 border_style=theme.BLUE_DEEP, box=box.SQUARE))

    def confirm(self, title: str, body) -> str:
        """Approval prompt. Accepts y/n/a/v, the full words, Enter = no."""
        self.console.print()
        self.console.print(Panel(body, title=f"{G['brand']} {title}",
                                 border_style="yellow", box=box.SQUARE))
        self.console.print(
            "  [bold yellow]approve?[/]  [green](y)[/]es   [red](n)[/]o   "
            "[cyan](a)[/]lways yes   [magenta](v)[/] never this session   [dim][Enter = no][/]")
        while True:
            try:
                raw = self.console.input(f"  [bold {theme.BLUE}]{G['cursor']}[/] ").strip().lower()
            except (EOFError, KeyboardInterrupt):
                return "n"
            if raw in CONFIRM_MAP:
                return CONFIRM_MAP[raw]
            if raw:
                self.console.print("  [dim]answer with y, n, a, or v[/dim]")

    def buttons(self, *items):
        """Clickable [ label ] chips (OSC 8 hyperlinks). items: (label, href)."""
        line = Text("  ")
        for i, (label, href) in enumerate(items):
            if i:
                line.append("   ")
            line.append(f"[ {label} ]", style=f"bold {theme.BLUE} link {href}")
        self.console.print(line)

    def input_line(self):
        self.console.print()
        try:
            return self.console.input(f"[bold {theme.BLUE}]{G['prompt']}[/] ")
        except EOFError:
            return None
